routes/index.py
import os
import uuid

from flask import (
    render_template,
    request,
    redirect,
    session,
    url_for,
    Blueprint,
    abort,
    send_from_directory,
)

from functools import wraps

from models.user import User
from models.reply import Reply
from models.topic import Topic

from utils import log

from routes import *

import json

import redis
cache = redis.StrictRedis()

main = Blueprint('index', __name__)


@main.route("/")
def index():
    u = current_user()
    # token = new_csrf_token()
    return render_template("index.html", user=u)
    # redirect(url_for('my_topic.index'))

@main.route("/register", methods=['POST'])
def register():
    # form = request.args
    form = request.form
    u = User.register(form)
    return redirect(url_for('.index'))


@main.route("/login", methods=['POST'])
def login():
    form = request.form
    u = User.validate_login(form)
    print('login user <{}>'.format(u))
    if u is None:
        # 转到 topic.index 页面
        return redirect(url_for('.index'))
    else:
        # session 中写入 user_id
        session['user_id'] = u.id
        # 设置 cookie 有效期为 永久
        session.permanent = True
        return redirect(url_for('my_topic.index'))


def created_topic(user_id):
    # O(n)
    ts = Topic.all(user_id=user_id)
    return ts

    # k = 'created_topic_{}'.format(user_id)
    # if cache.exists(k):
    #     v = cache.get(k)
    #     ts = json.loads(v)
    #     return ts
    # else:
    #     ts = Topic.all(user_id=user_id)
    #     v = json.dumps([t.json() for t in ts])
    #     cache.set(k, v)
    #     return ts


def replied_topic(user_id):
    # O(m*n)
    rs = Reply.all(user_id=user_id)
    ts = []
    for r in rs:
        t = Topic.one(id=r.topic_id)
        ts.append(t)
    return ts
    #
    # k = 'replied_topic_{}'.format(user_id)
    # if cache.exists(k):
    #     v = cache.get(k)
    #     ts = json.loads(v)
    #     return ts
    # else:
    #     rs = Reply.all(user_id=user_id)
    #     ts = []
    #     for r in rs:
    #         t = Topic.one(id=r.topic_id)
    #         ts.append(t)
    #
    #     v = json.dumps([t.json() for t in ts])
    #     cache.set(k, v)
    #
    #     return ts

# @main.route('/profile')
# def profile():
#     u = current_user()
#     if u is None:
#         return redirect(url_for('.index'))
#     else:
#         return render_template('personal.html', user=u)
#
@main.route('/profile')
def profile():
    print('running profile route')
    u = current_user()
    if u is None:
        return redirect(url_for('.index'))
    else:
        created = created_topic(u.id)
        replied = replied_topic(u.id)
        return render_template(
            'profile.html',
            user=u,
            created=created,
            replied=replied
        )


@main.route('/user/<string:username>')
def user_detail(username):
    print(username)
    u = User.one(username=username)
    if u is None:
        abort(404)
    else:
        user_id = User.one(username=username).id
        ms = Topic.all(user_id=user_id)
        ms.reverse()
        user_reply = Reply.all(user_id=user_id)
        rt = []
        for i in user_reply:
            t = Topic.one(id=i.topic_id)
            if t not in rt:
                rt.append(t)
            else:
                rt.remove(t)
                rt.append(t)
        rt.reverse()
        print(rt)
        return render_template('personal.html', user=u, ms=ms, rt=rt)


def not_found(e):
    return render_template('404.html')


@main.route('/image/add', methods=['POST'])
def avatar_add():
    file = request.files['avatar']

    # ../../root/.ssh/authorized_keys
    # filename = secure_filename(file.filename)
    suffix = file.filename.split('.')[-1]
    filename = '{}.{}'.format(str(uuid.uuid4()), suffix)
    path = os.path.join('images', filename)
    file.save(path)

    u = current_user()
    User.update(u.id, image='/images/{}'.format(filename))

    return redirect(url_for('.user_detail', username=u.username))


@main.route('/images/<filename>')
def image(filename):
    return send_from_directory('images', filename)


# def blueprint():
#     main = Blueprint('index', __name__)
#     main.route("/")(index)
#     main.route("/register", methods=['POST'])(register)
#     main.route("/login", methods=['POST'])(login)
#     main.route('/profile')(profile)
#     main.route('/user/<int:id>')(user_detail)
#
#     return main

@main.route('/setting')
def setting():
    u = current_user()
    token = new_csrf_token()
    return render_template('setting.html', token=token, user=u)


@main.route('/setting/username', methods=['POST'])
@csrf_required
def username_setting():
    form = request.form.to_dict()
    log('全部数据{}'.format(form))
    u = current_user()
    User.update(u.id, **form)
    # token = form['token']
    # csrf_tokens[token] = form['username']
    return redirect(url_for('.setting'))


@main.route('/setting/password', methods=['POST'])
@csrf_required
def password_setting():
    form = request.form.to_dict()
    u = current_user()
    log('第一次用户输出', u)
    if u.password == User.salted_password(form['old_pass']):
        new_pass = User.salted_password(form['new_pass'])
        form['password'] = new_pass
        log('传入的form', form)
        User.update(u.id, **form)
        u = current_user()
        log('第二次用户输出', u)
        return redirect(url_for('.setting'))
    else:
        return redirect(url_for('.index'))

routes/topic.py
from flask import (
    render_template,
    request,
    redirect,
    url_for,
    Blueprint,
)

from routes import current_user

from models.topic import Topic

from routes import (
    csrf_required,
    new_csrf_token,
    topic_required,
)

main = Blueprint('my_topic', __name__)


@main.route("/")
def index():
    ms = Topic.all()[::-1]
    u = current_user()
    token = new_csrf_token()
    return render_template("topic/index.html", ms=ms, user=u, token=token)


@main.route('/<int:id>')
# /topic/1
# @main.route('/')
# /topic?id=1
def detail(id):
    # id = int(request.args['id'])
    # http://localhost:3000/topic/1
    m = Topic.get(id)

    # 传递 topic 的所有 reply 到 页面中
    return render_template("topic/detail.html", topic=m)


@main.route("/add", methods=["POST"])
def add():
    form = request.form.to_dict()
    u = current_user()
    m = Topic.add(form, user_id=u.id)
    return redirect(url_for('.detail', id=m.id))


@main.route("/new")
def new():
    return render_template("topic/new.html")


# @main.route("/delete")
# def delete():
#     # form = request.form.to_dict()
#     u = current_user()
#     m = Topic.delete(user_id=u.id)
#     return redirect(url_for('.index'))

@main.route("/delete")
@csrf_required
@topic_required
# @login_required
def delete():
    id = int(request.args.get('id'))
    u = current_user()
    print('删除 topic 用户是', u, id)
    Topic.delete(id)
    return redirect(url_for('.index'))

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>bbs club</title>
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
</head>
<body>
    <form class="form-horizontal" method="post" action="{{ url_for('.register') }}">
        <div class="control-group">
            <label class="control-label">用户名</label>
            <div class="controls">
                <input type="text" class="input-xlarge" name="username">
            </div>
        </div>
        <div class="control-group">
            <label class="control-label">密码</label>
            <div class="controls">
                <input type="text" class="input-xlarge" name="password">
            </div>
        </div>
        <div class="form-actions" method="post" action="{{ url_for('.register') }}">
            <input type="submit" class="span-primary" value="注册">
        </div>
    </form>
    <form class="form-horizontal" method="post" action="{{ url_for('.login') }}">
        <div class="control-group">
            <label class="control-label">用户名</label>
            <div class="controls">
                <input type="text" class="input-xlarge" name="username">
            </div>
        </div>
        <div class="control-group">
            <label class="control-label">密码</label>
            <div class="controls">
                <input type="text" class="input-xlarge" name="password">
            </div>
        </div>
        <div class="form-actions">
            <input type="submit" class="span-primary" value="登录">
        </div>

        <h2><a href="{{ url_for('my_topic.index') }}">访客模式登录</a></h2>
    </form>
</body>
</html>

templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form method="POST" action="{{ url_for('.login') }}">
    <input type="text" name="user_name" placeholder="user_name">
    <button type="submit">提交</button>
</form>
</body>
</html>

templates/personal.html
{% extends "topic/base.html" %}
{% block title %}个人主页{% endblock%}
{% block main %}
<div id="main">
  <div id="sidebar">
  <div class="panel">
    <div class="header">
      <span class="col_fade">个人信息</span>
    </div>
    <div class="inner">
      <div class="user_card">
        <div>
          <a class="user_avatar" href="{{ url_for('index.user_detail', username=user.username) }}">
            <img src="{{ user.image }} ">
          </a>
          <span class="user_name"><a class="dark" href="{{ url_for('index.user_detail', username=user.username) }}">{{ user.username }}</a></span>
            <div class="board clearfix">
              <div class="floor">
                <span class="big">积分: 30 </span>
              </div>
            </div>
            <div class="space clearfix"></div>
            <span class="signature">
                “

                    {{ user.signature }}

                ”
            </span>
            </div>
          </div>
        </div>
      </div>
  </div>
  <div id="content">
  <div class="panel">
    <div class="header">
      <ul class="breadcrumb">
        <li><a href="https://cnodejs.org/">主页</a><span class="divider">/</span></li>
      </ul>
    </div>
    <div class="inner userinfo">
      <div class="user_big_avatar">
        <img src="{{ user.image }}" class="user_avatar" title="elvinn">
      </div>
      <a class="dark">{{ user.username }}</a>
      <p class="col_fade">注册时间 3 天前</p>
      
    </div>
  </div>

  <div class="panel">
    <div class="header">
      <span class="col_fade">最近创建的话题</span>
    </div>
    {% for t in ms %}
    <div class="cell">

  <a class="user_avatar pull-left" href="https://cnodejs.org/user/elvinn">
    <img src="{{ user.image }}" title="elvinn">
  </a>

  <span class="reply_count pull-left">
    <span class="count_of_replies" title="回复数">
      {{ t.replies() | count }}
    </span>
    <span class="count_seperator">/</span>
    <span class="count_of_visits" title="点击数">
      {{ t.views }}
    </span>
  </span>
  <a class="last_time pull-right" href="https://cnodejs.org/topic/5b82dd11632c7f422e5b815a#5b840d97fad9359e2e83124e">
    <img class="user_small_avatar" src="{{ user.image }}">
    <span class="last_active_time">11 小时前</span>
  </a>
  <div class="topic_title_wrapper">
    <a class="topic_title" href="{{ url_for('my_topic.detail', id=t.id) }}" title="每天阅读一个 npm 模块（2）- mem">
      {{ t.title }}
    </a>
  </div>
</div>
    {% endfor %}
  </div>

  <div class="panel">
    <div class="header">
      <span class="col_fade">最近参与的话题</span>
    </div>
    {% for r in rt %}
    <div class="cell">

  <a class="user_avatar pull-left" href="https://cnodejs.org/user/elvinn">
    <img src="{{ user.image }}" title="elvinn">
  </a>
  <span class="reply_count pull-left">
    <span class="count_of_replies" title="回复数">
      {{ r.replies() | count }}
    </span>
    <span class="count_seperator">/</span>
    <span class="count_of_visits" title="点击数">
      {{ r.views }}
    </span>
  </span>
  <a class="last_time pull-right" href="https://cnodejs.org/topic/5b82dd11632c7f422e5b815a#5b840d97fad9359e2e83124e">
    <img class="user_small_avatar" src="{{ user.image }}">
    <span class="last_active_time">11 小时前</span>
  </a>
  <div class="topic_title_wrapper">
    <a class="topic_title" href="{{ url_for('my_topic.detail', id=r.id) }}" title="每天阅读一个 npm 模块（2）- mem">
      {{ r.title }}
    </a>
  </div>
</div>
    {% endfor %}
    
  </div>
</div>



</div>

{% endblock %}

templates/profile.html
{% extends "topic/base.html" %}
{% block title %}个人主页{% endblock%}
{% block main %}
<div id="main">
  <div id="sidebar">
  <div class="panel">
    <div class="header">
      <span class="col_fade">个人信息</span>
    </div>
    <div class="inner">
      <div class="user_card">
        <div>
          <a class="user_avatar" href="{{ url_for('index.user_detail', username=user.username) }}">
            <img src="{{ user.image }} ">
          </a>
          <span class="user_name"><a class="dark" href="{{ url_for('index.user_detail', username=user.username) }}">{{ user.username }}</a></span>
            <div class="board clearfix">
              <div class="floor">
                <span class="big">积分: 30 </span>
              </div>
            </div>
            <div class="space clearfix"></div>
            <span class="signature">
                “

                    {{ user.signature }}

                ”
            </span>
            </div>
          </div>
        </div>
      </div>
  </div>
  <div id="content">
  <div class="panel">
    <div class="header">
      <ul class="breadcrumb">
        <li><a href="https://cnodejs.org/">主页</a><span class="divider">/</span></li>
      </ul>
    </div>
    <div class="inner userinfo">
      <div class="user_big_avatar">
        <img src="{{ user.image }}" class="user_avatar" title="elvinn">
      </div>
      <a class="dark">{{ user.username }}</a>
      <p class="col_fade">注册时间 3 天前</p>
      
    </div>
  </div>

  <div class="panel">
    <div class="header">
      <span class="col_fade">最近创建的话题</span>
    </div>
    {% for t in created %}
    <div class="cell">

  <a class="user_avatar pull-left" href="https://cnodejs.org/user/elvinn">
    <img src="{{ user.image }}" title="elvinn">
  </a>

  <span class="reply_count pull-left">
    <span class="count_of_replies" title="回复数">
      {{ t.replies() | count }}
    </span>
    <span class="count_seperator">/</span>
    <span class="count_of_visits" title="点击数">
      {{ t.views }}
    </span>
  </span>
  <a class="last_time pull-right" href="https://cnodejs.org/topic/5b82dd11632c7f422e5b815a#5b840d97fad9359e2e83124e">
    <img class="user_small_avatar" src="{{ user.image }}">
    <span class="last_active_time">11 小时前</span>
  </a>
  <div class="topic_title_wrapper">
    <a class="topic_title" href="{{ url_for('my_topic.detail', id=t.id) }}" title="每天阅读一个 npm 模块（2）- mem">
      {{ t.title }}
    </a>
  </div>
</div>
    {% endfor %}
  </div>

  <div class="panel">
    <div class="header">
      <span class="col_fade">最近参与的话题</span>
    </div>
    {% for r in replied %}
    <div class="cell">

  <a class="user_avatar pull-left" href="https://cnodejs.org/user/elvinn">
    <img src="{{ user.image }}" title="elvinn">
  </a>
  <span class="reply_count pull-left">
    <span class="count_of_replies" title="回复数">
      {{ r.replies() | count }}
    </span>
    <span class="count_seperator">/</span>
    <span class="count_of_visits" title="点击数">
      {{ r.views }}
    </span>
  </span>
  <a class="last_time pull-right" href="https://cnodejs.org/topic/5b82dd11632c7f422e5b815a#5b840d97fad9359e2e83124e">
    <img class="user_small_avatar" src="{{ user.image }}">
    <span class="last_active_time">11 小时前</span>
  </a>
  <div class="topic_title_wrapper">
    <a class="topic_title" href="{{ url_for('my_topic.detail', id=r.id) }}" title="每天阅读一个 npm 模块（2）- mem">
      {{ r.title }}
    </a>
  </div>
</div>
    {% endfor %}
    
  </div>
</div>



</div>

{% endblock %}

templates/setting.html
{% extends "topic/base.html" %}
{% block title %}个人主页{% endblock%}
{% block main %}
<div id="main">
  <div id="sidebar">
  <div class="panel">
    
    <div class="header">
      <span class="col_fade">个人信息</span>
    </div>
    <div class="inner">
      <div class="user_card">
  <div>
    <a class="user_avatar" href="{{ url_for('index.user_detail', username=user.username) }}">
      <img src="{{ user.image }} ">
    </a>
    <span class="user_name"><a class="dark" href="{{ url_for('index.user_detail', username=user.username) }}">{{ user.username }}</a></span>
    <div class="board clearfix">
      <div class="floor">
        <span class="big">积分: 30 </span>
      </div>
    </div>
    <div class="space clearfix"></div>
    <span class="signature">
        “
        {{ user.signature }}
        ”
    </span>
  </div>
</div>
    </div>
    
  </div>

  
  <div class="panel">
    <div class="inner">
      <a href="{{ url_for('my_topic.new') }}" id="create_topic_btn">
        <span class="span-success">发布话题</span>
      </a>
    </div>
  </div>
</div>


<div id="content">
  <div class="panel">
    <div class="header">
      <ul class="breadcrumb">
        <li><a href="https://cnodejs.org/">主页</a><span class="divider">/</span></li>
        <li class="active">设置</li>
      </ul>
    </div>
    <div class="inner">
      
      
      <form id="setting_form" class="form-horizontal" action="{{ url_for('.username_setting', token=token) }}" method="post">
        <div class="control-group">
          <label class="control-label" for="name">用户名</label>
          <div class="controls">
            <input class="input-xlarge readonly" id="name" name="username" size="30" type="text" value="{{ user.username }}">
          </div>
        </div>
        <div class="control-group">
          <label class="control-label" for="signature">个性签名</label>
          <div class="controls">
            <textarea class="input-xlarge" id="signature" name="signature" size="30"></textarea>
          </div>
        </div>
        <input type="hidden" id="action" name="action" value="change_setting">
        <input type="hidden" name="token" value="{{ token }}">

        <div class="form-actions">
          <input type="submit" class="span-primary submit_btn" data-loading-text="保存中.." value="保存设置">
        </div>
      </form>
    </div>
  </div>

  <div class="panel">
    <div class="header">
      <span class="col_fade">更改密码</span>
    </div>
    <div class="inner">
      <form id="change_pass_form" class="form-horizontal" action="{{ url_for('.password_setting', token=token) }}" method="post">
        <div class="control-group">
          <label class="control-label" for="old_pass">当前密码</label>

          <div class="controls">
            <input class="input-xlarge" type="password" id="old_pass" name="old_pass" size="30">
          </div>
        </div>
        <div class="control-group">
          <label class="control-label" for="new_pass">新密码</label>

          <div class="controls">
            <input class="input-xlarge" type="password" id="new_pass" name="new_pass" size="30">
          </div>
        </div>
        <input type="hidden" id="action" name="action" value="change_password">
        <input type="hidden" name="_csrf" value="79XMZL3C-aWx2YFkAt4XExi2oWnZwXaAn-is">

        <div class="form-actions">
          <input type="submit" class="span-primary submit_btn" data-loading-text="更改中.." value="更改密码">
        </div>
      </form>
    </div>
  </div>

  <div class="panel">
    <div class="header">
      <span class="col_fade">Access Token</span>
    </div>
    <div class="inner">
      <div>
      <form method="post"
      action="{{ url_for('.avatar_add')}}"
      enctype="multipart/form-data"
>
    <input type="file" name="avatar">
    <button type="submit">上传头像</button>
</form>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
  // qrcode generate
  var accessToken = "bc94212f-590a-403a-821b-ab70f731c8cc";
  new QRCode(document.getElementById("access-token-qrcode"), {
    text: accessToken,
    width: 200,
    height: 200,
  });
  // END qrcode generate
</script>

</div>
<div id="backtotop" style="display: none; top: 496px; right: 0px;">回到顶部</div>

<div id="sidebar-mask"></div>


<script>
  // google analytics
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script', "https://www.google-analytics.com/analytics.js",'ga');

  ga('create', 'UA-41753901-5', 'auto');
  ga('send', 'pageview');
</script>



<div style="display:none;">
  <script src="./CNode：Node.js专业中文社区_files/z_stat.php" language="JavaScript"></script><script src="./CNode：Node.js专业中文社区_files/core.php" charset="utf-8" type="text/javascript"></script><a href="http://www.cnzz.com/stat/website.php?web_id=1254020586" target="_blank" title="站长统计">站长统计</a>
</div>
{% endblock %}