models/topic.py
import time

from sqlalchemy import String, Integer, Column, Text, UnicodeText, Unicode

from models import Model
from models.base_model import SQLMixin, db
from models.user import User
from models.reply import Reply


class Topic(SQLMixin, db.Model):
    views = Column(Integer, nullable=False, default=0)
    title = Column(Unicode(50), nullable=False)
    content = Column(UnicodeText, nullable=False)
    user_id = Column(Integer, nullable=False)

    @classmethod
    def add(cls, form, user_id):
        form['user_id'] = user_id
        m = super().new(form)
        return m

    @classmethod
    def get(cls, id):
        m = cls.one(id=id)
        m.views += 1
        m.save()
        return m

    def user(self):
        u = User.one(id=self.user_id)
        return u

    def replies(self):
        ms = Reply.all(topic_id=self.id)
        return ms

    def reply_count(self):
        count = len(self.replies())
        return count

routes/index.py
import os
import uuid

from flask import (
    render_template,
    request,
    redirect,
    session,
    url_for,
    Blueprint,
    abort,
    send_from_directory,
)

from functools import wraps

from models.user import User
from models.reply import Reply
from models.topic import Topic

from utils import log

from routes import *

import json

import redis
cache = redis.StrictRedis()

main = Blueprint('index', __name__)


@main.route("/")
def index():
    u = current_user()
    # token = new_csrf_token()
    return render_template("index.html", user=u)
    # redirect(url_for('my_topic.index'))

@main.route("/register", methods=['POST'])
def register():
    # form = request.args
    form = request.form
    u = User.register(form)
    return redirect(url_for('.index'))


@main.route("/login", methods=['POST'])
def login():
    form = request.form
    u = User.validate_login(form)
    print('login user <{}>'.format(u))
    if u is None:
        # 转到 topic.index 页面
        return redirect(url_for('.index'))
    else:
        # session 中写入 user_id
        session['user_id'] = u.id
        # 设置 cookie 有效期为 永久
        session.permanent = True
        return redirect(url_for('my_topic.index'))


def created_topic(user_id):
    # O(n)
    ts = Topic.all(user_id=user_id)
    return ts

    # k = 'created_topic_{}'.format(user_id)
    # if cache.exists(k):
    #     v = cache.get(k)
    #     ts = json.loads(v)
    #     return ts
    # else:
    #     ts = Topic.all(user_id=user_id)
    #     v = json.dumps([t.json() for t in ts])
    #     cache.set(k, v)
    #     return ts


def replied_topic(user_id):
    # O(m*n)
    rs = Reply.all(user_id=user_id)
    ts = []
    for r in rs:
        t = Topic.one(id=r.topic_id)
        ts.append(t)
    return ts
    #
    # k = 'replied_topic_{}'.format(user_id)
    # if cache.exists(k):
    #     v = cache.get(k)
    #     ts = json.loads(v)
    #     return ts
    # else:
    #     rs = Reply.all(user_id=user_id)
    #     ts = []
    #     for r in rs:
    #         t = Topic.one(id=r.topic_id)
    #         ts.append(t)
    #
    #     v = json.dumps([t.json() for t in ts])
    #     cache.set(k, v)
    #
    #     return ts

# @main.route('/profile')
# def profile():
#     u = current_user()
#     if u is None:
#         return redirect(url_for('.index'))
#     else:
#         return render_template('personal.html', user=u)
#
@main.route('/profile')
def profile():
    print('running profile route')
    u = current_user()
    if u is None:
        return redirect(url_for('.index'))
    else:
        created = created_topic(u.id)
        replied = replied_topic(u.id)
        return render_template(
            'profile.html',
            user=u,
            created=created,
            replied=replied
        )


@main.route('/user/<string:username>')
def user_detail(username):
    print(username)
    u = User.one(username=username)
    if u is None:
        abort(404)
    else:
        user_id = User.one(username=username).id
        ms = Topic.all(user_id=user_id)
        ms.reverse()
        user_reply = Reply.all(user_id=user_id)
        rt = []
        for i in user_reply:
            t = Topic.one(id=i.topic_id)
            if t not in rt:
                rt.append(t)
            else:
                rt.remove(t)
                rt.append(t)
        rt.reverse()
        print(rt)
        return render_template('personal.html', user=u, ms=ms, rt=rt)


def not_found(e):
    return render_template('404.html')


@main.route('/image/add', methods=['POST'])
def avatar_add():
    file = request.files['avatar']

    # ../../root/.ssh/authorized_keys
    # filename = secure_filename(file.filename)
    suffix = file.filename.split('.')[-1]
    filename = '{}.{}'.format(str(uuid.uuid4()), suffix)
    path = os.path.join('images', filename)
    file.save(path)

    u = current_user()
    User.update(u.id, image='/images/{}'.format(filename))

    return redirect(url_for('.user_detail', username=u.username))


@main.route('/images/<filename>')
def image(filename):
    return send_from_directory('images', filename)


# def blueprint():
#     main = Blueprint('index', __name__)
#     main.route("/")(index)
#     main.route("/register", methods=['POST'])(register)
#     main.route("/login", methods=['POST'])(login)
#     main.route('/profile')(profile)
#     main.route('/user/<int:id>')(user_detail)
#
#     return main

@main.route('/setting')
def setting():
    u = current_user()
    token = new_csrf_token()
    return render_template('setting.html', token=token, user=u)


@main.route('/setting/username', methods=['POST'])
@csrf_required
def username_setting():
    form = request.form.to_dict()
    log('全部数据{}'.format(form))
    u = current_user()
    User.update(u.id, **form)
    # token = form['token']
    # csrf_tokens[token] = form['username']
    return redirect(url_for('.setting'))


@main.route('/setting/password', methods=['POST'])
@csrf_required
def password_setting():
    form = request.form.to_dict()
    u = current_user()
    log('第一次用户输出', u)
    if u.password == User.salted_password(form['old_pass']):
        new_pass = User.salted_password(form['new_pass'])
        form['password'] = new_pass
        log('传入的form', form)
        User.update(u.id, **form)
        u = current_user()
        log('第二次用户输出', u)
        return redirect(url_for('.setting'))
    else:
        return redirect(url_for('.index'))

routes/reply.py
from flask import (
    request,
    redirect,
    url_for,
    Blueprint,
)

from routes import current_user

from models.reply import Reply


main = Blueprint('my_reply', __name__)


@main.route("/add", methods=["POST"])
def add():
    form = request.form.to_dict()
    u = current_user()
    print('DEBUG', form)
    m = Reply.add(form, user_id=u.id)
    return redirect(url_for('my_topic.detail', id=m.topic_id))

routes/topic.py
from flask import (
    render_template,
    request,
    redirect,
    url_for,
    Blueprint,
)

from routes import current_user

from models.topic import Topic

from routes import (
    csrf_required,
    new_csrf_token,
    topic_required,
)

main = Blueprint('my_topic', __name__)


@main.route("/")
def index():
    ms = Topic.all()[::-1]
    u = current_user()
    token = new_csrf_token()
    return render_template("topic/index.html", ms=ms, user=u, token=token)


@main.route('/<int:id>')
# /topic/1
# @main.route('/')
# /topic?id=1
def detail(id):
    # id = int(request.args['id'])
    # http://localhost:3000/topic/1
    m = Topic.get(id)

    # 传递 topic 的所有 reply 到 页面中
    return render_template("topic/detail.html", topic=m)


@main.route("/add", methods=["POST"])
def add():
    form = request.form.to_dict()
    u = current_user()
    m = Topic.add(form, user_id=u.id)
    return redirect(url_for('.detail', id=m.id))


@main.route("/new")
def new():
    return render_template("topic/new.html")


# @main.route("/delete")
# def delete():
#     # form = request.form.to_dict()
#     u = current_user()
#     m = Topic.delete(user_id=u.id)
#     return redirect(url_for('.index'))

@main.route("/delete")
@csrf_required
@topic_required
# @login_required
def delete():
    id = int(request.args.get('id'))
    u = current_user()
    print('删除 topic 用户是', u, id)
    Topic.delete(id)
    return redirect(url_for('.index'))

templates/topic/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/css/style.css">
<head>
<body>

<div class="navbar">
  <div class="navbar-inner">
    <div class="container">
      <a class="brand" href="{{ url_for('.index') }}">
        <img src="/static/pic/cnodejs_light.svg">
      </a>

      <form id="search_form" class="navbar-search" action="">
        <input type="text" id="q" name="q" class="search-query span3" value="">
      </form>
      <ul class="nav pull-right">
        <li><a href="{{ url_for('my_topic.index') }}">首页</a></li>
        <li><a href="{{ url_for('index.setting') }}">设置</a></li>
        <li>
          <a href="{{ url_for('.index') }}" data-method="post" rel="nofollow">退出</a>
        </li>
      </ul>
      <a class="btn btn-navbar" id="responsive-sidebar-trigger">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
    </div>
  </div>
</div>

{% block main %}
{% endblock %}
<div id="footer">
  <div id="footer_main">
    <div class="links">
      <a class="dark" href="">2018－2019 , all rights reserved myself</a>
      |
      <a class="dark" href=""></a>
    </div>

    <div class="col_fade">

    </div>


  </div>
</div>

</body>

templates/topic/detail.html
{% extends "topic/base.html" %}
{% block title %}{{ topic.title }}{% endblock%}
{% block main %}
<div id="main">
    <div id="content">
        <div class='panel'>
            <div class='header topic_header'>
            <span class="topic_full_title">
                {{ topic.title }}
            </span>
                <div class="changes">
                    <span>
                        发布于 {{ topic.created_time | format_time }}
                    </span>
                    <span>
                        作者
                        <a href="{{ url_for('index.user_detail', username=topic.user().username) }}">
                        {{ topic.user().username }}
                        </a>
                        {# 作者 {{ User.one(id=topic.user_id).username }} #}
                    </span>
                    <span>
                        {{ topic.views }} 次浏览
                    </span>
                    <span>
                        来自 问答
                    </span>
                </div>
            </div>

            <div class='inner topic'>
                <div class='topic_content'>
                    <div class="markdown-text">{{ topic.content }}</div>
                </div>
            </div>
        </div>
    </div>

    <div class='panel'>
        <div class='header'>
            <span class='col_fade'>
                <!-- 过滤器 -->
                {{ topic.replies() | count }} 回复
            </span>
        </div>
        {% for r in topic.replies() %}
        {% set u = r.user() %}
        <div class='cell reply_area reply_item'>
            <div class='user_info'>
                <a class='dark reply_author'>
                    {{ u.username }}
                </a>
                <a class="reply_time">
                    {{ loop.index }}楼 / {{ loop.length }}楼 •
                    <span class="gua-time" data-created_time="{{ r.created_time }}"></span>
                </a>
            </div>
            <div class='user_action'>
                    <span>
                        <i class="fa up_btn
                          fa-thumbs-o-up
                          invisible" title="喜欢"></i>
                        <span class="up-count">
                        </span>
                    </span>
            </div>
            <div class='reply_content from-leiwei1991'>
                <div class="markdown-text">{{ r.content }}</div>
            </div>
        </div>
        {% endfor %}
    </div>
    <div>
        <form action="{{ url_for('my_reply.add') }}" method="post">
            <input type="hidden" name="topic_id" value="{{ topic.id }}">
            <textarea name="content"></textarea>
            <button>添加回复</button>
        </form>
    </div>
</div>
<script src="https://cdn.bootcss.com/marked/0.3.19/marked.min.js"></script>
<script src="https://cdn.bootcss.com/prism/1.13.0/prism.js"></script>
<script src="https://cdn.bootcss.com/prism/1.13.0/plugins/autoloader/prism-autoloader.min.js"></script>
<script>
    var e = function (sel) {
        return document.querySelector(sel)
    }

    var es = function (sel) {
        return document.querySelectorAll(sel)
    }

    var markContents = function () {
        // markdown -> html 的处理放在高亮前面
        // 因为高亮是针对 html 格式的
        // lang -> language 不需要转 prism 自动转了
        var contentDivs = es('.markdown-text')
        for (var i = 0; i < contentDivs.length; i++) {
            var contentDiv = contentDivs[i]
            console.log('pre marked', contentDiv.textContent, contentDiv.innerHTML)
            var content = marked(contentDiv.textContent)
            console.log('after marked', content)
            contentDiv.innerHTML = content
        }
    }

    var highlight = function() {
         // 自动加载对应的语言 不然要手动加入各个语言的 js
        Prism.plugins.autoloader.languages_path = 'https://cdn.bootcss.com/prism/1.13.0/components/'
    }

    var registerTimer = function () {
        setInterval(function () {
            var times = es('.gua-time')
            for (var i = 0; i < times.length; i++) {
                var t = times[i]
                var time = Number(t.dataset.created_time)
                var now = Math.floor(new Date() / 1000)
                var delta = now - time
                var s = `${delta} 秒前`
                t.innerText = s
            }
        }, 1000)
    }

    var __main = function () {
        markContents()
        highlight()
        registerTimer()
    }

    __main()

</script>
{% endblock %}

templates/topic/index.html
{% extends "topic/base.html" %}
{% block title %}论坛主页{% endblock%}
{% block main %}
    <div id="main">
        <div id="sidebar">
            <div class="panel">
                <div class="header">
                    <span class="col_fade">个人信息</span>
                </div>
                <div class="inner">

                    <div class="user_card">
                        <div>
                          <a class="user_avatar" href="{{ url_for('index.user_detail', username=user.username) }}">
                            <img src="{{ user.image }} ">
                          </a>
                          <span class="user_name"><a class="dark" href="{{ url_for('index.user_detail', username=user.username) }}">{{ user.username }}</a></span>
                          <div class="board clearfix">
                              <div class="floor">
                                <span class="big">积分: 30 </span>
                              </div>
                          </div>
                          <div class="space clearfix"></div>
                          <span class="signature">
                                “
                                    {{ user.signature }}
                                ”
                          </span>
                        </div>
                    </div>
                </div>
                <a href="{{ url_for('my_topic.new') }}" class="create_topic_btn">
                    <span class="span-success">发布话题</span>
                </a>
            </div>
        </div>
        <div id="content">
            <div class="panel">
                <div class="inner post">
                    <div class="topic_list">
                        {% for t in ms %}
                        <div class="cell">
                            <div class="topic_title_wrapper">
                                <a class="topic_title" href="{{ url_for('my_topic.detail', id=t.id) }}">
                                    {{ t.title }}
                                </a>
                                <span>{{ t.replies() | count }} / {{ t.views }}</span>
                                {# count(t.replies()) #}
                                {# <span>{{ t.reply_count() }} / {{ t.views }}</span> #}
                                <a class="topic_title" href="{{ url_for('my_topic.delete', id=t.id, token=token) }}">
                                删除
                                </a>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/topic/new.html
{% extends "topic/base.html" %}
{% block title %}发表新帖{% endblock%}
{% block main %}
    <div id="main">
        <div id="content">
            <div class="panel">
                <div class="inner post">
<form id="create_topic_form" method="post" action="{{ url_for('.add') }}">
    <fieldset>
        <textarea autofocus class='span9' id='title'
                  name='title' rows='1'
                  placeholder="标题字数 10 字以上"></textarea>
        <div class='markdown_editor in_editor'>
          <div class='markdown_in_editor'>
            <textarea class='editor' name='content' rows='20' placeholder='文章支持 Markdown 语法, 请注意标记代码'></textarea>
            <div class='editor_buttons'>
              <input type="submit" class='span-primary submit_btn' data-loading-text="提交中" value="提交">
            </div>
          </div>
        </div>
    </fieldset>
</form>
                </div>
            </div>
        </div>
    </div>

<script>
  (sfunction () {
    var editor = new Editor();
    editor.render($('.editor')[0]);
  })();
</script>
{% endblock %}